name: CV workflow

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build_CV:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CV
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install numpy tqdm requests ads

      - name: Install latex
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra    

      - name: Run makeCV
        run: python makeCV.py

      - name: Compile latex
        run: |
          pdflatex CV.tex
          pdflatex CVshort.tex
          pdflatex publist.tex
          pdflatex talklist.tex

      - name: Check PDFs
        run: |
          ls -lh *.pdf

      - name: Rename PDFs
        run: |
          cp CV.pdf ChiaraAnselmo_fullCV.pdf
          cp CVshort.pdf ChiaraAnselmo_shortCV.pdf
          cp publist.pdf ChiaraAnselmo_publist.pdf
          cp talklist.pdf ChiaraAnselmo_talklist.pdf

      - name: Create GitHub release
        run: |
          gh release delete latest --yes || true
          git push --delete origin latest || true
          gh release create latest \
          ChiaraAnselmo_fullCV.pdf \
          ChiaraAnselmo_shortCV.pdf \
          ChiaraAnselmo_publist.pdf \
          ChiaraAnselmo_talklist.pdf \
          --notes "Automated CV update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
