name: CV workflow

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build_CV:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CV
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install numpy tqdm requests ads

      - name: Install latex
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra    

      - name: Run makeCV
        run: python makeCV.py

      - name: Compile latex
        run: |
          pdflatex CV.tex
          pdflatex CVshort.tex
          pdflatex publist.tex
          pdflatex talklist.tex

      - name: Check PDFs
        run: |
          ls -lh *.pdf

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: CV-pdfs
          path: "*.pdf"
