name: CV workflow

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build_CV:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CV
        uses: actions/checkout@v4
        with:
          path: CV

      - name: Checkout website
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install numpy tqdm requests ads

      - name: Run makeCV
        run: python makeCV.py
        env:
          ADS_TOKEN: ${{ secrets.ADS_TOKEN}}

      - name: Install latex
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra gh

      - name: Compile CVs
        run: |
          for f in CV CVshort publist talklist; do
            pdflatex "$f".tex

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: CV-pdfs
          path: |
            CV.pdf
            CVshort.pdf
            publist.pdf
            talklist.pdf
